const SUPABASE_URL="https://bbgydodrydbruqnugrjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_wzyjqh9paWFBt2i733ZTvQ_SkhPVh1u";
const games=[{id:"wakless",name:"WAKLESS",desc:"لعبة مستقلة من ETOGAME. متاحة حالياً لـ Android و Windows.",version:"1.0.0",platforms:["Android","Windows"],updated:"2026-10-03",android:"#",windows:"#"}];
const updates=[{date:"2026-10-03",title:"إطلاق ETOGAME",text:"تم إطلاق الواجهة الأولى للمنصة مع تصميم متجاوب، حركات انتقالية وصفحة WAKLESS."}];
const grid=document.getElementById("gamesGrid"),list=document.getElementById("updatesList"),search=document.getElementById("search"),modal=document.getElementById("gameModal"),modalContent=document.getElementById("modalContent");
async function loadGames(){try{const r=await fetch(SUPABASE_URL+"/rest/v1/games?select=*&published=eq.true&order=featured.desc,created_at.desc",{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:"Bearer "+SUPABASE_PUBLISHABLE_KEY}});if(!r.ok)throw new Error();const rows=await r.json();if(rows.length){games.splice(0,games.length,...rows.map(g=>({id:g.slug,name:g.title,desc:g.short_description||"",version:g.version||"1.0.0",platforms:["Android","Windows"],updated:(g.updated_at||"").slice(0,10),android:"#",windows:"#"})));renderGames(search.value);const count=document.getElementById("gameCount");if(count)count.textContent=games.length}}catch(e){console.warn("ETOGAME database unavailable; using fallback data.")}}
function renderGames(q=""){const items=games.filter(g=>(g.name+" "+g.desc).toLowerCase().includes(q.toLowerCase()));grid.innerHTML=items.length?items.map(g=>`<article class="game-card reveal show"><div class="cover"><div class="cover-title">WAKE<span>LESS</span></div></div><div class="game-info"><h3>${g.name}</h3><p>${g.desc}</p><div class="badges">${g.platforms.map(x=>`<span class="badge">${x}</span>`).join("")}<span class="badge">v${g.version}</span></div><div class="game-bottom"><span class="badge">آخر تحديث ${g.updated}</span><button class="details-btn" onclick="openGame('${g.id}')">التفاصيل ←</button></div></div></article>`).join(""):`<div class="update">لا توجد نتائج مطابقة.</div>`}
function renderUpdates(){list.innerHTML=updates.map(u=>`<article class="update reveal show"><time>${u.date}</time><div><h3>${u.title}</h3><p>${u.text}</p></div></article>`).join("")}
window.openGame=id=>{const g=games.find(x=>x.id===id);if(!g)return;modalContent.innerHTML=`<span class="section-kicker">GAME DETAILS</span><h2>${g.name}</h2><p>${g.desc}</p><div class="badges">${g.platforms.map(x=>`<span class="badge">${x}</span>`).join("")}<span class="badge">v${g.version}</span></div><div class="download-row"><a class="download disabled" href="#">⬇ تحميل Android</a><a class="download disabled" href="#">⬇ تحميل Windows</a></div>`;modal.classList.remove("hidden");document.body.style.overflow="hidden"}
document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",()=>{modal.classList.add("hidden");document.body.style.overflow=""}));search.addEventListener("input",e=>renderGames(e.target.value));
document.getElementById("loginBtn").onclick=()=>toast("تسجيل الدخول وقاعدة البيانات سيتم تفعيلهما في الخطوة التالية 🔐");
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("light");toast("تم تبديل المظهر.")};
function toast(t){const el=document.getElementById("toast");el.textContent=t;el.classList.remove("hidden");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.add("hidden"),2800)}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("show")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>io.observe(e));
renderGames();renderUpdates();loadGames();